version: "3.8"

services: 
  bank: 
    build: https://github.com/riuGlobal/bank-server.git#develop
    env_file: 
      - .env

  bank-web:
    depends_on:
      - bank
    build: https://github.com/riuGlobal/bank-client.git#master
    volumes:
      - ${PWD}/.env:/bank-web/.env
